package com.unicamp.mc322.projeto.Interface;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;


public class InterfaceGraficaCamp extends javax.swing.JFrame {


    public InterfaceGraficaCamp() {
    	getContentPane().setFont(new Font("Arial", Font.PLAIN, 10));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jblVidaNexusPlayer1 = new javax.swing.JLabel();
        jblVidaNexusPlayer2 = new javax.swing.JLabel();
        jblTipoDeTurnoPlayer1 = new javax.swing.JLabel();
        jblTipoDeTurnoPlayer2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jblManaPlayer1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jblManaFeiticoPlayer1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jblManaPlayer2 = new javax.swing.JLabel();
        jblManaFeiticoPlayer2 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel19 = new javax.swing.JLabel();
        bntP1Carta12 = new javax.swing.JButton();
        bntP1Carta15 = new javax.swing.JButton();
        bntP1Carta16 = new javax.swing.JButton();
        bntP1Carta17 = new javax.swing.JButton();
        bntP1Carta13 = new javax.swing.JButton();
        bntP1Carta14 = new javax.swing.JButton();
        bntP1Carta18 = new javax.swing.JButton();
        bntP1Carta19 = new javax.swing.JButton();
        bntP1Carta20 = new javax.swing.JButton();
        bntP1Carta21 = new javax.swing.JButton();
        bntP1Carta22 = new javax.swing.JButton();
        bntP1Carta23 = new javax.swing.JButton();
        bntP1_Mao_0 = new javax.swing.JButton();
        bntP1_Mao_0.setFont(new Font("Tahoma", Font.PLAIN, 9));
        bntP2Carta1 = new javax.swing.JButton();
        bntP2Carta2 = new javax.swing.JButton();
        bntP2Carta3 = new javax.swing.JButton();
        bntP2Carta4 = new javax.swing.JButton();
        bntP2Carta5 = new javax.swing.JButton();
        bntP2Carta6 = new javax.swing.JButton();
        bntP2Carta7 = new javax.swing.JButton();
        bntP2Carta8 = new javax.swing.JButton();
        bntP2Carta9 = new javax.swing.JButton();
        bntP2Carta10 = new javax.swing.JButton();
        bntP2Carta11 = new javax.swing.JButton();
        bntP2Carta12 = new javax.swing.JButton();
        bntP1Carta6 = new javax.swing.JButton();
        bntP1Carta7 = new javax.swing.JButton();
        bntP1Carta8 = new javax.swing.JButton();
        bntP1Carta9 = new javax.swing.JButton();
        bntP1Carta10 = new javax.swing.JButton();
        bntP1Carta11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new Dimension(850, 850));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Nexus Jogador 2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Nexus Jogador 1");

        jblVidaNexusPlayer1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jblVidaNexusPlayer1.setText("20");

        jblVidaNexusPlayer2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jblVidaNexusPlayer2.setText("20");

        jblTipoDeTurnoPlayer1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jblTipoDeTurnoPlayer1.setText("Defesa");

        jblTipoDeTurnoPlayer2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jblTipoDeTurnoPlayer2.setText("Ataque");

        jButton1.setText("Turno do Oponente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 153));
        jLabel3.setText("Mana de Feitiço");

        jblManaPlayer1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jblManaPlayer1.setForeground(new java.awt.Color(153, 153, 255));
        jblManaPlayer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblManaPlayer1.setText("5");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 255));
        jLabel5.setText("Mana");

        jblManaFeiticoPlayer1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jblManaFeiticoPlayer1.setForeground(new java.awt.Color(255, 153, 153));
        jblManaFeiticoPlayer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblManaFeiticoPlayer1.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 255));
        jLabel6.setText("Mana");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 153));
        jLabel4.setText("Mana de Feitiço");

        jblManaPlayer2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jblManaPlayer2.setForeground(new java.awt.Color(153, 153, 255));
        jblManaPlayer2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblManaPlayer2.setText("5");

        jblManaFeiticoPlayer2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jblManaFeiticoPlayer2.setForeground(new java.awt.Color(255, 153, 153));
        jblManaFeiticoPlayer2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblManaFeiticoPlayer2.setText("0");

        jLayeredPane2.setBackground(new java.awt.Color(153, 255, 153));
        jLayeredPane2.setOpaque(true);

        jLabel19.setBackground(new java.awt.Color(153, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Feitico");
        jLabel19.setToolTipText("");
        jLabel19.setAutoscrolls(true);
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel19.setOpaque(true);

        bntP1Carta12.setText("jButton2");

        bntP1Carta15.setText("jButton2");
        bntP1Carta15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntP1Carta15ActionPerformed(evt);
            }
        });

        bntP1Carta16.setText("jButton2");
        bntP1Carta16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntP1Carta16ActionPerformed(evt);
            }
        });

        bntP1Carta17.setText("jButton2");
        bntP1Carta17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntP1Carta17ActionPerformed(evt);
            }
        });

        bntP1Carta13.setText("jButton2");
        bntP1Carta13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntP1Carta13ActionPerformed(evt);
            }
        });

        bntP1Carta14.setText("jButton2");
        bntP1Carta14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntP1Carta14ActionPerformed(evt);
            }
        });

        bntP1Carta18.setText("jButton2");

        bntP1Carta19.setText("jButton2");
        bntP1Carta19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntP1Carta19ActionPerformed(evt);
            }
        });

        bntP1Carta20.setText("jButton2");
        bntP1Carta20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntP1Carta20ActionPerformed(evt);
            }
        });

        bntP1Carta21.setText("jButton2");
        bntP1Carta21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntP1Carta21ActionPerformed(evt);
            }
        });

        bntP1Carta22.setText("jButton2");
        bntP1Carta22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntP1Carta22ActionPerformed(evt);
            }
        });

        bntP1Carta23.setText("jButton2");
        bntP1Carta23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntP1Carta23ActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(bntP1Carta12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(bntP1Carta15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(bntP1Carta16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(bntP1Carta17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(bntP1Carta13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(bntP1Carta14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(bntP1Carta18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(bntP1Carta19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(bntP1Carta20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(bntP1Carta21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(bntP1Carta22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(bntP1Carta23, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(bntP1Carta18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bntP1Carta19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bntP1Carta22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bntP1Carta20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bntP1Carta21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bntP1Carta23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(bntP1Carta12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bntP1Carta13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bntP1Carta16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bntP1Carta14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bntP1Carta15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bntP1Carta17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntP1Carta18, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntP1Carta19, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntP1Carta20, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntP1Carta21, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntP1Carta22, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntP1Carta23, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntP1Carta12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntP1Carta13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntP1Carta14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntP1Carta15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntP1Carta16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntP1Carta17, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bntP1_Mao_0.setText("<html>Campeao 0<br /><br />Vida: 10<br />Ataque: 5</html>");

        bntP2Carta1.setText("jButton2");

        bntP2Carta2.setText("jButton2");

        bntP2Carta3.setText("jButton2");

        bntP2Carta4.setText("jButton2");

        bntP2Carta5.setText("jButton2");

        bntP2Carta6.setText("jButton2");
        bntP2Carta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntP2Carta6ActionPerformed(evt);
            }
        });

        bntP2Carta7.setText("jButton2");

        bntP2Carta8.setText("jButton2");

        bntP2Carta9.setText("jButton2");

        bntP2Carta10.setText("jButton2");

        bntP2Carta11.setText("jButton2");

        bntP2Carta12.setText("jButton2");
        bntP2Carta12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntP2Carta12ActionPerformed(evt);
            }
        });

        bntP1Carta6.setText("jButton2");
        bntP1Carta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntP1Carta6ActionPerformed(evt);
            }
        });

        bntP1Carta7.setText("jButton2");
        bntP1Carta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntP1Carta7ActionPerformed(evt);
            }
        });

        bntP1Carta8.setText("jButton2");
        bntP1Carta8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntP1Carta8ActionPerformed(evt);
            }
        });

        bntP1Carta9.setText("jButton2");
        bntP1Carta9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntP1Carta9ActionPerformed(evt);
            }
        });

        bntP1Carta10.setText("jButton2");
        bntP1Carta10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntP1Carta10ActionPerformed(evt);
            }
        });

        bntP1Carta11.setText("jButton2");
        
        bntP1_Mao = new JButton();
        bntP1_Mao.setText("<html>Campeao 1<br /><br />Vida: 10<br />Ataque: 5</html>");
        bntP1_Mao.setFont(new Font("Tahoma", Font.PLAIN, 9));
        
        bntP1_Mao_1 = new JButton();
        bntP1_Mao_1.setText("<html>Campeao 2<br /><br />Vida: 10<br />Ataque: 5</html>");
        bntP1_Mao_1.setFont(new Font("Tahoma", Font.PLAIN, 9));
        
        bntP1_Mao_2 = new JButton();
        bntP1_Mao_2.setText("<html>Campeao 3<br /><br />Vida: 10<br />Ataque: 5</html>");
        bntP1_Mao_2.setFont(new Font("Tahoma", Font.PLAIN, 9));
        
        bntP1_Mao_3 = new JButton();
        bntP1_Mao_3.setText("<html>Campeao 4<br /><br />Vida: 10<br />Ataque: 5</html>");
        bntP1_Mao_3.setFont(new Font("Tahoma", Font.PLAIN, 9));
        
        bntP1_Mao_4 = new JButton();
        bntP1_Mao_4.setText("<html>Campeao 5<br /><br />Vida: 10<br />Ataque: 5</html>");
        bntP1_Mao_4.setFont(new Font("Tahoma", Font.PLAIN, 9));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(layout.createSequentialGroup()
        									.addGap(38)
        									.addComponent(jblVidaNexusPlayer1))
        								.addComponent(jLabel1)
        								.addGroup(layout.createSequentialGroup()
        									.addGap(39)
        									.addComponent(jblVidaNexusPlayer2))
        								.addComponent(jLabel2))
        							.addGap(18)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLayeredPane2, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addGroup(layout.createSequentialGroup()
        									.addGap(31)
        									.addGroup(layout.createParallelGroup(Alignment.LEADING)
        										.addGroup(layout.createSequentialGroup()
        											.addComponent(bntP2Carta7, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        											.addGap(18)
        											.addComponent(bntP2Carta8, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        											.addGap(18)
        											.addComponent(bntP2Carta9, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        											.addGap(18)
        											.addComponent(bntP2Carta10, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        											.addGap(18)
        											.addComponent(bntP2Carta11, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        											.addGap(18)
        											.addComponent(bntP2Carta12, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
        										.addGroup(layout.createSequentialGroup()
        											.addComponent(bntP2Carta1, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        											.addGap(18)
        											.addComponent(bntP2Carta2, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        											.addGap(18)
        											.addComponent(bntP2Carta3, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        											.addGap(18)
        											.addComponent(bntP2Carta4, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        											.addGap(18)
        											.addComponent(bntP2Carta5, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        											.addGap(18)
        											.addComponent(bntP2Carta6, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)))
        									.addGap(29)))
        							.addGap(18)
        							.addComponent(jButton1))
        						.addGroup(layout.createSequentialGroup()
        							.addGap(663)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 109, GroupLayout.PREFERRED_SIZE)
        								.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        									.addComponent(jblTipoDeTurnoPlayer2)
        									.addComponent(jLabel3))
        								.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 109, GroupLayout.PREFERRED_SIZE)
        								.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        									.addComponent(jblTipoDeTurnoPlayer1)
        									.addComponent(jLabel4)))))
        					.addPreferredGap(ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        							.addComponent(jblManaPlayer1, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
        							.addComponent(jblManaFeiticoPlayer1, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE))
        						.addComponent(jblManaFeiticoPlayer2, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jblManaPlayer2, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(157)
        							.addComponent(bntP1Carta11, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
        						.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        							.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(bntP1_Mao_0, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
        							.addGap(17)))
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(38)
        							.addComponent(bntP1Carta6, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(bntP1Carta9, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(bntP1Carta7, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(bntP1Carta8, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(bntP1Carta10, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
        						.addGroup(layout.createSequentialGroup()
        							.addGap(1)
        							.addComponent(bntP1_Mao, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(bntP1_Mao_1, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(bntP1_Mao_2, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(bntP1_Mao_3, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(bntP1_Mao_4, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)))
        					.addGap(17)))
        			.addGap(1))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(20)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(bntP2Carta1, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        				.addComponent(bntP2Carta2, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        				.addComponent(bntP2Carta3, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        				.addComponent(bntP2Carta4, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        				.addComponent(bntP2Carta5, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        				.addComponent(bntP2Carta6, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(bntP2Carta7, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        				.addComponent(bntP2Carta8, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        				.addComponent(bntP2Carta9, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        				.addComponent(bntP2Carta10, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        				.addComponent(bntP2Carta11, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        				.addComponent(bntP2Carta12, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE))
        			.addGap(13)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        					.addComponent(jLayeredPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGroup(layout.createSequentialGroup()
        						.addComponent(jblVidaNexusPlayer2)
        						.addPreferredGap(ComponentPlacement.RELATED)
        						.addComponent(jLabel1)
        						.addGap(35)
        						.addComponent(jLabel2)
        						.addPreferredGap(ComponentPlacement.RELATED)
        						.addComponent(jblVidaNexusPlayer1)
        						.addGap(97)))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jblTipoDeTurnoPlayer1)
        					.addGap(29)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel4)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jblManaFeiticoPlayer2)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(jblManaPlayer2)))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
        					.addGap(15)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(22)
        							.addComponent(jblManaFeiticoPlayer1))
        						.addComponent(jblManaPlayer1)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel5)
        							.addGap(5)
        							.addComponent(jLabel3)
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(jblTipoDeTurnoPlayer2)))))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(bntP1Carta11, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        				.addComponent(bntP1Carta6, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        				.addComponent(bntP1Carta7, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        				.addComponent(bntP1Carta8, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        				.addComponent(bntP1Carta9, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        				.addComponent(bntP1Carta10, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(36)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(bntP1_Mao_0, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        						.addComponent(bntP1_Mao, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(37)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(bntP1_Mao_1, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        						.addComponent(bntP1_Mao_2, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        						.addComponent(bntP1_Mao_3, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        						.addComponent(bntP1_Mao_4, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE))))
        			.addContainerGap(70, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void bntP2Carta6ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void bntP2Carta12ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void bntP1Carta6ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void bntP1Carta7ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void bntP1Carta8ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void bntP1Carta9ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void bntP1Carta10ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void bntP1Carta13ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void bntP1Carta14ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void bntP1Carta15ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void bntP1Carta16ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void bntP1Carta17ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void bntP1Carta19ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void bntP1Carta20ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void bntP1Carta21ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void bntP1Carta22ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void bntP1Carta23ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    // Variables declaration - do not modify                     
    private javax.swing.JButton bntP1_Mao_0;
    private javax.swing.JButton bntP1Carta10;
    private javax.swing.JButton bntP1Carta11;
    private javax.swing.JButton bntP1Carta12;
    private javax.swing.JButton bntP1Carta13;
    private javax.swing.JButton bntP1Carta14;
    private javax.swing.JButton bntP1Carta15;
    private javax.swing.JButton bntP1Carta16;
    private javax.swing.JButton bntP1Carta17;
    private javax.swing.JButton bntP1Carta18;
    private javax.swing.JButton bntP1Carta19;
    private javax.swing.JButton bntP1Carta20;
    private javax.swing.JButton bntP1Carta21;
    private javax.swing.JButton bntP1Carta22;
    private javax.swing.JButton bntP1Carta23;
    private javax.swing.JButton bntP1Carta6;
    private javax.swing.JButton bntP1Carta7;
    private javax.swing.JButton bntP1Carta8;
    private javax.swing.JButton bntP1Carta9;
    private javax.swing.JButton bntP2Carta1;
    private javax.swing.JButton bntP2Carta10;
    private javax.swing.JButton bntP2Carta11;
    private javax.swing.JButton bntP2Carta12;
    private javax.swing.JButton bntP2Carta2;
    private javax.swing.JButton bntP2Carta3;
    private javax.swing.JButton bntP2Carta4;
    private javax.swing.JButton bntP2Carta5;
    private javax.swing.JButton bntP2Carta6;
    private javax.swing.JButton bntP2Carta7;
    private javax.swing.JButton bntP2Carta8;
    private javax.swing.JButton bntP2Carta9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLabel jblManaFeiticoPlayer1;
    private javax.swing.JLabel jblManaFeiticoPlayer2;
    private javax.swing.JLabel jblManaPlayer1;
    private javax.swing.JLabel jblManaPlayer2;
    private javax.swing.JLabel jblTipoDeTurnoPlayer1;
    private javax.swing.JLabel jblTipoDeTurnoPlayer2;
    private javax.swing.JLabel jblVidaNexusPlayer1;
    private javax.swing.JLabel jblVidaNexusPlayer2;
    private JButton bntP1_Mao;
    private JButton bntP1_Mao_1;
    private JButton bntP1_Mao_2;
    private JButton bntP1_Mao_3;
    private JButton bntP1_Mao_4;
}
